import psutil
a = psutil.cpu_count(logical=True)
b = psutil.cpu_percent(percpu=True)
c = psutil.cpu_stats()
t = psutil.cpu_times_percent()
d = psutil.cpu_times()
print(d)
print(t)
print(c)
print(a)
print(b)
mem = psutil.virtual_memory()
print(mem.total,mem.used,mem.free)
print(psutil.swap_memory())