name = input("请输入姓名: ")
company = input("请输入公司名称: ")
phone = input("请输入联系电话: ")
job_title = input("请输入你的职位: ")
Email = input("请输入你的电子邮箱: ")

print("*"*50)
print(company)
print("")
print(name,"(%s)" % job_title)
print("")
print("电话：%s" % phone)
print("邮箱：%s" % Email)
print("*"*50)