L=[1,2,3]
L.append('abc')
L.append(['a','b','c'])
print(L[3][1])
""" print(L)
L.insert(0,'asd')
print(L)
L.insert(1,0)
print(L)
L.extend(['aaa','bbb'])
print(L)
L.extend(('asdafg',123))
print(L)
L.extend({'1':3,'345':'1fh'})
print(L) """